version: '3.1'

services:

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ledarit
      WORDPRESS_DB_PASSWORD: ledarit_game_fi
      WORDPRESS_DB_NAME: ledarit_db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    volumes:
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wordpress:/var/www/html

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: ledarit_db
      MYSQL_USER: ledarit
      MYSQL_PASSWORD: ledarit_game_fi
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!

volumes:
  wordpress:
  db:
